//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.Data.Pluralsight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TM.Data.Pluralsight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training provider site url can&apos;t be null.
        /// </summary>
        internal static string ArgumentNull_SiteUrl {
            get {
                return ResourceManager.GetString("ArgumentNull_SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was occured while parse {0} node..
        /// </summary>
        internal static string CatalogNodeParseException_Message {
            get {
                return ResourceManager.GetString("CatalogNodeParseException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading data from web..
        /// </summary>
        internal static string DownloadException_Message {
            get {
                return ResourceManager.GetString("DownloadException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training provider with name = &apos;{0}&apos; not found in db.
        /// </summary>
        internal static string EntityNotFound_TrainingProvider {
            get {
                return ResourceManager.GetString("EntityNotFound_TrainingProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.Id must be set on the course.
        /// </summary>
        internal static string InvalidOperation_CategoryIdMustBeSetOnTheCourse {
            get {
                return ResourceManager.GetString("InvalidOperation_CategoryIdMustBeSetOnTheCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize(...) method invoke required.
        /// </summary>
        internal static string InvalidOperation_PluralsightCatalog_InitializeMethodInvokeRequired {
            get {
                return ResourceManager.GetString("InvalidOperation_PluralsightCatalog_InitializeMethodInvokeRequired", resourceCulture);
            }
        }
    }
}
