//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.Data.Update.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TM.Data.Update.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving archive to {0}. See inner exception for details..
        /// </summary>
        internal static string ArchiveSaveException_Message {
            get {
                return ResourceManager.GetString("ArchiveSaveException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while processing authors changes. See inner exception for details..
        /// </summary>
        internal static string ChangesProcessorException_AuthorsChanges_Message {
            get {
                return ResourceManager.GetString("ChangesProcessorException_AuthorsChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while processing categories changes. See inner exception for details..
        /// </summary>
        internal static string ChangesProcessorException_CategoriesChanges_Message {
            get {
                return ResourceManager.GetString("ChangesProcessorException_CategoriesChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while processing courses changes. See inner exception for details..
        /// </summary>
        internal static string ChangesProcessorException_CoursesChanges_Message {
            get {
                return ResourceManager.GetString("ChangesProcessorException_CoursesChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training provider with name = &apos;{0}&apos; not found in db.
        /// </summary>
        internal static string EntityNotFound_TrainingProvider {
            get {
                return ResourceManager.GetString("EntityNotFound_TrainingProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author move statistic not supported.
        /// </summary>
        internal static string InvalidOperation_AuthorMoveStatistic {
            get {
                return ResourceManager.GetString("InvalidOperation_AuthorMoveStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category move statistic not supported.
        /// </summary>
        internal static string InvalidOperation_CategoryMoveStatistic {
            get {
                return ResourceManager.GetString("InvalidOperation_CategoryMoveStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating {0} media content. See inner exception for details..
        /// </summary>
        internal static string MediaContentUpdateException_Message {
            get {
                return ResourceManager.GetString("MediaContentUpdateException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive directory &apos;{0}&apos; not found.
        /// </summary>
        internal static string TrainingCatalogException_ArchiveDirectoryNotFound {
            get {
                return ResourceManager.GetString("TrainingCatalogException_ArchiveDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while initializating catalog. See inner exception for details..
        /// </summary>
        internal static string TrainingCatalogInitializationException_Message {
            get {
                return ResourceManager.GetString("TrainingCatalogInitializationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating {0} trainings catalog. See inner exception for details..
        /// </summary>
        internal static string TrainingCatalogUpdateException_Message {
            get {
                return ResourceManager.GetString("TrainingCatalogUpdateException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual update.
        /// </summary>
        internal static string UpdateEventDescription_ManualEvent {
            get {
                return ResourceManager.GetString("UpdateEventDescription_ManualEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled update.
        /// </summary>
        internal static string UpdateEventDescription_ScheduledEvent {
            get {
                return ResourceManager.GetString("UpdateEventDescription_ScheduledEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating authors info. See inner exception for details..
        /// </summary>
        internal static string UpdateProcessorException_AuthorsUpdate_Message {
            get {
                return ResourceManager.GetString("UpdateProcessorException_AuthorsUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating categories info. See inner exception for details..
        /// </summary>
        internal static string UpdateProcessorException_CategoriesUpdate_Message {
            get {
                return ResourceManager.GetString("UpdateProcessorException_CategoriesUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating courses info. See inner exception for details..
        /// </summary>
        internal static string UpdateProcessorException_CoursesUpdate_Message {
            get {
                return ResourceManager.GetString("UpdateProcessorException_CoursesUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Can not process update, because database is in update state&quot;.
        /// </summary>
        internal static string UpdateService_CannotUpdateBecauseDatabaseIsInUpdateState {
            get {
                return ResourceManager.GetString("UpdateService_CannotUpdateBecauseDatabaseIsInUpdateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author with name =&apos;{0}&apos; and social links already exists in db. Existing author id&apos;s: {1}..
        /// </summary>
        internal static string UpdateServiceException_AuthorAlreadyInDb_Message {
            get {
                return ResourceManager.GetString("UpdateServiceException_AuthorAlreadyInDb_Message", resourceCulture);
            }
        }
    }
}
